#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
secret = secrets.token_hex(32)
#This is specific to you module, so you need to change it accordingly.
# Form bricks configuration
host = data.get('host')
WEBAPP_URL=f'https://{host}'
ENCRYPTION_KEY=secret
NEXTAUTH_SECRET =secret
NEXTAUTH_URL=f'https://{host}'
CRON_SECRET=secret

# SMTP Configuration
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
## Set the default values
SMTP_HOST=smtp_settings['host']
# OPTIONAL: Defines the port to use for sending emails.
SMTP_PORT=smtp_settings['port']
# OPTIONAL: Defines the username to use with the SMTP server.
SMTP_USERNAME=smtp_settings['username']
# OPTIONAL: Defines the password to use with the SMTP server.
SMTP_PASSWORD=smtp_settings['password']
SMTP_FROM_NAME=f'"From Bricks" <{smtp_settings["username"]}>'
# REQUIRED: Defines the email address to use as the from address.
SMTP_ENCRYPTION=smtp_settings['tls_verify']

bricks = {
    'WEBAPP_URL': WEBAPP_URL,
    'ENCRYPTION_KEY': ENCRYPTION_KEY,
    'NEXTAUTH_SECRET': NEXTAUTH_SECRET,
    'NEXTAUTH_URL': NEXTAUTH_URL,
    'CRON_SECRET': CRON_SECRET,
    'SMTP_HOST': SMTP_HOST,
    'SMTP_PORT': SMTP_PORT,
    'SMTP_USER': SMTP_USERNAME,
    'SMTP_PASSWORD': SMTP_PASSWORD,
    'MAIL_FROM': SMTP_FROM_NAME,
    'SMTP_SECURE_ENABLED': SMTP_ENCRYPTION
}
agent.write_envfile("bricks.env", bricks)
# just before starting systemd unit
#agent.dump_env()
